version: '2.1'
orbs:
  sam: circleci/aws-sam-serverless@2.1.0
jobs:
  test_my_api:
    executor: sam/default
    steps:
      - run: echo "Run your tests here"
workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-production
          stack-name: sam-app
          template: ../aws-sam/build/template.yaml
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-4ttmarv49u95



